### ISSUE TITLE
Add a command line session for windows

### ISSUE THREAD

**Issue by drapergeek** [railsbridge-boston/railsbridge-boston#65] opened 2013-06-25 02:08 UTC
Despite being nearly identical, I had a few students say they wanted a separate command line for windows session just so they could feel like we were covering all areas.

This may have just been a failure to really explain that the session applied to windows. Just putting this out there for discussion.

**Comment by danchoi** [comment] 2013-08-26 17:46
Proposal in #86 would put everyone regardless of laptop OS on Ubuntu command line.

**Comment by janetriley** [comment] 2013-11-10 21:44
Since we rolled out Vagrant ( per #86 ),  and since the issue is 5 months old, I'm going to close this issue.   Please re-open if it still needs attention.

**Closed as completed by janetriley** 2013-11-10 21:44 UTC
Labels: curriculum / structure, command line
